version: '3.9'

services:
  backend:
    build: .
    depends_on:
      - db
    entrypoint: .docker/entrypoint.sh
    container_name: challenge-produza-backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    networks:
      - backend

  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    container_name: challenge-produza-db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=docker
    networks:
      - backend

networks:
  backend:
    driver: bridge
