version: '3.9'

services:
  backend:
    build: .
    entrypoint: .docker/entrypoint.sh
    depends_on:
      - db
    container_name: challenge-produza-backend
    ports:
      - "8080:8080"
      - "5555:5555"
    volumes:
      - .:/home/node/app
    networks:
      - challenge-produza-network

  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    container_name: challenge-produza-db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/dbdata
    environment:
      - POSTGRES_PASSWORD=docker
    networks:
      - challenge-produza-network

networks:
  challenge-produza-network:
    driver: bridge
